name: publish

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Publish
      run: cargo publish --index https://github.com/rust-lang/crates.io-index --token ${{ secrets.CARGO_TOKEN }}
